### ISSUE TITLE
Shader error

### ISSUE THREAD

**Issue by Claymaver2000** [Dcai169/Destiny-API-Ripper-Extension#16]
I've tried quite a few shaders and i keep getting this error. (i have replaced my name with "%USERNAME%")

DARE v1.6.1
DCG v1.7.11

Hashes: 1363705634
No hashes given.

Shader flag found, getting shader data...
Shader rip failed!
Unhandled exception.
System.IO.FileNotFoundException: Could not find file 'C:\Users\%USERNAME%\AppData\Local\Temp\destiny-api-ripper-extension\Amethyst Veil-3U6nMk\1363705634\shader.json'.
File name: 'C:\Users\%USERNAME%\AppData\Local\Temp\destiny-api-ripper-extension\Amethyst Veil-3U6nMk\1363705634\shader.json'
at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
at System.IO.File.ReadAllBytes(String path)
at DestinyColladaGenerator.GamePresets.generatePresets(String game, String shaderData, String name)
at DestinyColladaGenerator.Program.Main(String[] args)

**Comment by Claymaver2000** [comment]
![image](https://user-images.githubusercontent.com/48605875/213898876-8f069c68-73d8-4150-86bb-df4b1b125f72.png)

**Comment by Claymaver2000** [comment]
not sure what it was but a full removal and re-download of every thing seemed to work
